version: '3.1'

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: "admin123**"
      POSTGRES_DB: robotics_lab_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: devops/Dockerfile
    container_name: robotics_lab_system_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/robotics_lab_system
      SPRING_DATASOURCE_USERNAME: user_admin
      SPRING_DATASOURCE_PASSWORD: "admin123**"
      SPRING_PROFILES_ACTIVE: local
      API_SECURITY_TOKEN_SECRET: dev-local-secret
      DEBUG: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
