version: '3.1'

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: admin123**
      POSTGRES_DB: robotics_lab_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:12-alpine
    container_name: postgres_test_container
    environment:
      POSTGRES_USER: test_admin
      POSTGRES_PASSWORD: test123**
      POSTGRES_DB: robotics_lab_system_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
