version: '3.1'

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: TCCRoboticslabsystem
      POSTGRES_PASSWORD: dhfrhiuhchgeryetrtbc%%$$$##A
      POSTGRES_DB: robotics_lab_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
